package com.dlb.chess.bitboard;

import java.util.Set;
import java.util.TreeSet;
import java.util.function.Consumer;

import com.dlb.chess.board.enums.CastlingRight;
import com.dlb.chess.board.enums.Piece;
import com.dlb.chess.board.enums.PieceType;
import com.dlb.chess.board.enums.PromotionPieceType;
import com.dlb.chess.board.enums.Side;
import com.dlb.chess.board.enums.Square;
import com.dlb.chess.common.Nulls;
import com.dlb.chess.common.constants.CastlingConstants;
import com.dlb.chess.common.model.MoveSpecification;
import com.dlb.chess.enums.CastlingCheck;
import com.dlb.chess.model.LegalMove;
import com.dlb.chess.model.LegalMoveKind;
import com.dlb.chess.moves.CastlingUtility;
import com.google.common.collect.ImmutableList;

/**
 * Converts a bare {@link MoveSpecification} (as produced by {@link BitboardPosition#legalMoves}) into a fully-typed
 * {@link LegalMove} record. The converter determines the moving piece and captured piece from the position, plus the
 * {@link LegalMoveKind} from the move shape:
 *
 * <ul>
 * <li>{@link LegalMoveKind#CASTLING} - when {@code moveSpec.castlingMove()} is non-NONE.</li>
 * <li>{@link LegalMoveKind#PROMOTION} - when {@code moveSpec.promotionPieceType()} is non-NONE.</li>
 * <li>{@link LegalMoveKind#PAWN_TWO_SQUARE_ADVANCE} - pawn moving two ranks.</li>
 * <li>{@link LegalMoveKind#EN_PASSANT_CAPTURE} - pawn moving diagonally onto an empty square.</li>
 * <li>{@link LegalMoveKind#NORMAL} - everything else.</li>
 * </ul>
 *
 * <p>
 * This is the Phase 2 prerequisite for porting {@code Board.getLegalMoves()} and the unwinnability analyzers off the
 * StaticPosition-backed move pipeline.
 */
public final class BitboardLegalMoveFactory {

  private BitboardLegalMoveFactory() {
  }

  public static LegalMove toLegalMove(BitboardPosition position, MoveSpecification moveSpec, Side movingSide) {
    if (movingSide != Side.WHITE && movingSide != Side.BLACK) {
      throw new IllegalArgumentException("toLegalMove requires Side.WHITE or Side.BLACK, got " + movingSide);
    }
    if (moveSpec.castlingMove() != com.dlb.chess.board.enums.CastlingMove.NONE) {
      final Piece kingPiece = movingSide == Side.WHITE ? Piece.WHITE_KING : Piece.BLACK_KING;
      return new LegalMove(moveSpec, kingPiece, Piece.NONE, LegalMoveKind.CASTLING);
    }

    final Square from = moveSpec.fromSquare();
    final Square to = moveSpec.toSquare();
    final Piece movingPiece = position.get(from);
    if (movingPiece == Piece.NONE) {
      throw new IllegalArgumentException("No piece on the from-square " + from.getName());
    }

    final boolean isPawn = movingPiece.getPieceType() == PieceType.PAWN;
    final boolean diagonalPawnMove = isPawn && from.getFile() != to.getFile();
    final boolean toEmpty = position.isEmpty(to);

    final Piece capturedPiece;
    if (!toEmpty) {
      capturedPiece = position.get(to);
    } else if (diagonalPawnMove) {
      // En-passant: captured pawn on the same rank as `from` (one rank back from `to`).
      capturedPiece = movingSide == Side.WHITE ? Piece.BLACK_PAWN : Piece.WHITE_PAWN;
    } else {
      capturedPiece = Piece.NONE;
    }

    final LegalMoveKind kind;
    if (moveSpec.promotionPieceType() != PromotionPieceType.NONE) {
      kind = LegalMoveKind.PROMOTION;
    } else if (isPawn && Math.abs(from.getRank().getNumber() - to.getRank().getNumber()) == 2) {
      kind = LegalMoveKind.PAWN_TWO_SQUARE_ADVANCE;
    } else if (diagonalPawnMove && toEmpty) {
      kind = LegalMoveKind.EN_PASSANT_CAPTURE;
    } else {
      kind = LegalMoveKind.NORMAL;
    }

    return new LegalMove(moveSpec, movingPiece, capturedPiece, kind);
  }

  /**
   * Full legal-move generation for the production pipeline: non-castling moves are generated by
   * {@link BitboardPosition#legalMoves} and run through {@link #toLegalMove}; castling moves are computed inline via
   * {@link #emitCastlingLegalMoves} using {@link CastlingUtility}'s bitboard overloads. Returns an
   * {@link ImmutableList} sorted by {@link LegalMove#compareTo}, matching the public contract of the previous
   * {@code AbstractLegalMoves.calculateLegalMoves} path.
   */
  public static ImmutableList<LegalMove> calculateLegalMoves(BitboardPosition bitboardPosition, Side havingMove,
      CastlingRight castlingRight, long enPassantBit) {
    final Set<LegalMove> result = new TreeSet<>();
    calculateLegalMovesInto(result::add, bitboardPosition, havingMove, castlingRight, enPassantBit);
    return Nulls.copyOfList(result);
  }

  /**
   * Sink-based variant of {@link #calculateLegalMoves}: emits the same {@link LegalMove}s to {@code sink} but in the
   * underlying move generator's natural traversal order (non-castling first, then castling king-side / queen-side),
   * rather than {@link LegalMove#compareTo} order. No {@link Set} / {@link TreeSet} / {@link ImmutableList} is
   * allocated by this method - the search hot path passes a per-depth reusable buffer's {@code add} method as the sink.
   * The order-sorting set-based {@link #calculateLegalMoves} wraps this with a {@link TreeSet}-collecting sink so
   * Board's public-API contract is preserved unchanged.
   */
  public static void calculateLegalMovesInto(Consumer<LegalMove> sink, BitboardPosition bitboardPosition,
      Side havingMove, CastlingRight castlingRight, long enPassantBit) {
    bitboardPosition.legalMovesInto(spec -> sink.accept(toLegalMove(bitboardPosition, spec, havingMove)), havingMove,
        enPassantBit);
    emitCastlingLegalMoves(sink, bitboardPosition, havingMove, castlingRight);
  }

  /**
   * Emits the legal castling moves for {@code havingMove} (king-side and queen-side, in that order) to {@code sink},
   * using {@link CastlingUtility}'s bitboard-overload castling checks. Moved here from {@code KingCastlingLegalMoves}
   * so the production legal-move pipeline does not depend on the relocated {@code com.dlb.chess.moves.*LegalMoves}
   * subtree (which lives in {@code src/test/} as the differential-test oracle).
   */
  private static void emitCastlingLegalMoves(Consumer<LegalMove> sink, BitboardPosition bitboardPosition,
      Side havingMove, CastlingRight castlingRight) {
    if (havingMove == Side.WHITE) {
      if (CastlingUtility.calculateQueenSideCastlingCheck(bitboardPosition, havingMove,
          castlingRight) == CastlingCheck.SUCCESS) {
        sink.accept(CastlingConstants.WHITE_QUEEN_SIDE_CASTLING_MOVE);
      }
      if (CastlingUtility.calculateKingSideCastlingCheck(bitboardPosition, havingMove,
          castlingRight) == CastlingCheck.SUCCESS) {
        sink.accept(CastlingConstants.WHITE_KING_SIDE_CASTLING_MOVE);
      }
    } else if (havingMove == Side.BLACK) {
      if (CastlingUtility.calculateQueenSideCastlingCheck(bitboardPosition, havingMove,
          castlingRight) == CastlingCheck.SUCCESS) {
        sink.accept(CastlingConstants.BLACK_QUEEN_SIDE_CASTLING_MOVE);
      }
      if (CastlingUtility.calculateKingSideCastlingCheck(bitboardPosition, havingMove,
          castlingRight) == CastlingCheck.SUCCESS) {
        sink.accept(CastlingConstants.BLACK_KING_SIDE_CASTLING_MOVE);
      }
    } else {
      throw new IllegalArgumentException("emitCastlingLegalMoves requires Side.WHITE or Side.BLACK, got " + havingMove);
    }
  }
}
