// Copyright (C) 2020-2026 Daniel Baechli
// SPDX-License-Identifier: GPL-3.0-only

package io.github.dlbbld.ashlarchess.test.unwinnability.againstchasolver;

import java.nio.file.Path;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import io.github.dlbbld.ashlarchess.exceptions.ProgrammingMistakeException;
import io.github.dlbbld.ashlarchess.internal.Nulls;
import io.github.dlbbld.ashlarchess.test.ConfigurationTestConstants;
import io.github.dlbbld.ashlarchess.test.common.utility.FileUtility;
import io.github.dlbbld.ashlarchess.test.unwinnability.againstchasolver.model.ChasolverUnwinnabilityVerdicts;
import io.github.dlbbld.ashlarchess.unwinnability.UnwinnabilityFullVerdict;
import io.github.dlbbld.ashlarchess.unwinnability.UnwinnabilityQuickVerdict;

/**
 * Reads the pre-generated chasolver oracle, produced from Miguel Ambrona's Rust {@code chasolver} over the same
 * distinct final FENs as the cha (C++) oracle. Regenerated by
 * {@code GenerateChasolverUnwinnabilityOracle}.
 */
public final class ChasolverUnwinnabilityOracle {

  private static final Path ORACLE_PATH = Nulls.pathResolve(ConfigurationTestConstants.PROJECT_ROOT_FOLDER_PATH,
      "src/test/resources/oracle/chasolver/ashlar-pgn/unwinnability.tsv");
  private static final Map<String, ChasolverUnwinnabilityVerdicts> VERDICT_BY_FEN = readOracle();

  private ChasolverUnwinnabilityOracle() {
  }

  public static ChasolverUnwinnabilityVerdicts get(String fen) {
    if (!VERDICT_BY_FEN.containsKey(fen)) {
      throw new IllegalArgumentException("No chasolver unwinnability oracle row for FEN: " + fen);
    }
    return Nulls.get(VERDICT_BY_FEN, fen);
  }

  public static boolean contains(String fen) {
    return VERDICT_BY_FEN.containsKey(fen);
  }

  private static Map<String, ChasolverUnwinnabilityVerdicts> readOracle() {
    final List<String> lines = FileUtility.readFileLines(ORACLE_PATH);
    if (lines.isEmpty()) {
      throw new ProgrammingMistakeException("The chasolver unwinnability oracle file is empty");
    }
    final String expectedHeader = "fen\tfullWhite\tfullBlack\tquickWhite\tquickBlack";
    if (!expectedHeader.equals(Nulls.get(lines, 0))) {
      throw new ProgrammingMistakeException("Unexpected chasolver unwinnability oracle header");
    }

    final Map<String, ChasolverUnwinnabilityVerdicts> result = new HashMap<>();
    for (int i = 1; i < lines.size(); i++) {
      final String line = Nulls.get(lines, i);
      final String[] itemArray = Nulls.split(line, "\t");
      if (itemArray.length != 5) {
        throw new ProgrammingMistakeException("Invalid chasolver unwinnability oracle row: " + line);
      }
      final String fen = Nulls.get(itemArray, 0);
      if (result.containsKey(fen)) {
        throw new ProgrammingMistakeException("Duplicate chasolver unwinnability oracle row for FEN: " + fen);
      }
      final ChasolverUnwinnabilityVerdicts verdicts = new ChasolverUnwinnabilityVerdicts(
          UnwinnabilityFullVerdict.valueOf(Nulls.get(itemArray, 1)),
          UnwinnabilityFullVerdict.valueOf(Nulls.get(itemArray, 2)),
          UnwinnabilityQuickVerdict.valueOf(Nulls.get(itemArray, 3)),
          UnwinnabilityQuickVerdict.valueOf(Nulls.get(itemArray, 4)));
      result.put(fen, verdicts);
    }
    return result;
  }
}
