// Copyright (C) 2020-2026 Daniel Baechli
// SPDX-License-Identifier: GPL-3.0-only

package io.github.dlbbld.ashlarchess.bitboard.internal;

import io.github.dlbbld.ashlarchess.exceptions.ProgrammingMistakeException;

/**
 * Slider attacks by magic-bitboard lookup: one multiply, one shift and one array read per query, independent of how
 * far the piece actually sees.
 *
 * <p>
 * The idea is to hash the occupancy bits that can affect the answer. For a given square only the squares along its own
 * rays matter, and not even all of those - the last square of each ray cannot block anything beyond itself, so it is
 * left out of the mask. That leaves at most 12 relevant bits for a rook and 9 for a bishop. A per-square multiplier
 * (the "magic") maps each occupancy subset onto an index in that square's table.
 *
 * <p>
 * Two properties make this safe to rely on. The tables are filled from {@link SliderRayAttacks}, so this class cannot
 * invent an attack set the ray walk would not produce. And the fill is checked as it runs: whenever two occupancies
 * land on the same index, their attack sets must be identical, otherwise initialization fails. So a magic constant
 * that does not suit its mask cannot produce a silently wrong table - it cannot produce a table at all.
 *
 * <p>
 * The magics are searched offline rather than at startup, and {@code MagicNumberGeneratorRun} in the test tree is the
 * search that produced them. Searching here instead would cost roughly 300 ms of class initialization, which is far
 * too much to spend on the first slider query in a library. Keeping the search reachable matters because the constants
 * are only valid for the masks below: change a mask and initialization will reject them, and the generator is then how
 * a matching set is re-derived.
 */
public final class MagicSliderAttacks {

  private static final int SQUARES = 64;

  // Generated by MagicNumberGeneratorRun. Valid only for the masks computed below; verified on every initialization.
  private static final long[] BISHOP_MAGIC = {
      0x0010015004004042L, 0x0010302089204084L, 0x900840810204A000L, 0x8804440488040103L, 0x0304042000400000L,
      0x010088200A022000L, 0x0208E80808680540L, 0x0080208208200220L, 0x1008446008450100L, 0xAA00032802008200L,
      0x20400802005A0080L, 0x0200040400890320L, 0x8098011040780000L, 0xC044420110085A02L, 0x040A030419208800L,
      0x8404804218010820L, 0x00104F0410022800L, 0x021000081000A891L, 0x0988023000411220L, 0x0808016220A04000L,
      0x0001000820086020L, 0x00020005015A2200L, 0x0820540401080848L, 0x8810404421080800L, 0x2044C00004101408L,
      0x020110C004500200L, 0x0004880450002020L, 0x82040100A0200880L, 0x0081020064008400L, 0x0006002106101000L,
      0x024C408810480400L, 0x8020882410820800L, 0x0041080B00405004L, 0x4102012040301202L, 0x2003140403020808L,
      0x8100110800440040L, 0x0401100400008021L, 0x06080200880C1000L, 0x00040124000600C0L, 0x1481184100008400L,
      0x0004020840050400L, 0x0001010120001000L, 0x4810108410000100L, 0x8000A02058001500L, 0x000904210C017A02L,
      0x00201610E20018C0L, 0x4162900404801102L, 0x0001014102080900L, 0x2400808820108820L, 0x00E04104192009B3L,
      0x0040020200920000L, 0x90282B0241108210L, 0x9041009002020800L, 0x1010500290090004L, 0x604288110C009040L,
      0x1090102099104004L, 0x04A104A2100C0C10L, 0x0006002108023008L, 0x10001045C2089088L, 0x0000408020421208L,
      0x0000C00441050100L, 0x2001000820040423L, 0x01A042080A20A200L, 0x40022008160A4840L,
  };

  // Generated by MagicNumberGeneratorRun. Valid only for the masks computed below; verified on every initialization.
  private static final long[] ROOK_MAGIC = {
      0x1080004008801020L, 0x0140100040002004L, 0x0200204008120080L, 0x2080100080080204L, 0x8600101820240600L,
      0x0080040002008001L, 0x040010040800C201L, 0x0200002218810044L, 0x8001800040018021L, 0x834280400280A000L,
      0x0208801000200080L, 0x0201804800801001L, 0x0112002010040A00L, 0x0202800200800400L, 0x44A0808001008200L,
      0x48420004020054A1L, 0x4002888001400062L, 0x0020028040008020L, 0x2404120042008021L, 0x80020200100A2040L,
      0x0444050010880100L, 0x4C10808004000200L, 0x0005040010280281L, 0x000002002A408D04L, 0x0140004080008020L,
      0x2040200880400084L, 0x0050200080100080L, 0x0500090100100020L, 0x0240080080800400L, 0x0101000300180400L,
      0x0020010400882230L, 0x0A41442200004891L, 0x1010804000801022L, 0x4480804000802001L, 0x4100801000802000L,
      0x2008840800801000L, 0x4A20800800800400L, 0x0442102008010440L, 0x0108080104002290L, 0x0882008042000104L,
      0x8840204000808002L, 0x0002010020820041L, 0x0120001000808028L, 0x2070090410010020L, 0x0051008800050010L,
      0x0002100420080140L, 0x0000010842040030L, 0x0100098244020025L, 0x8101042480084100L, 0x1205200140100840L,
      0x1000228202124600L, 0x0040080080100080L, 0x0810500801000500L, 0x8012040002008080L, 0x000C010882100400L,
      0x4054040D30804200L, 0x2000210010488001L, 0x0201002240008015L, 0x0420401020030209L, 0x1012482050000501L,
      0x201A000410200802L, 0x0802000110488402L, 0x0002080210010084L, 0x0200910080240042L,
  };

  private static final long[] BISHOP_MASK = new long[SQUARES];
  private static final long[] ROOK_MASK = new long[SQUARES];
  private static final int[] BISHOP_SHIFT = new int[SQUARES];
  private static final int[] ROOK_SHIFT = new int[SQUARES];
  private static final int[] BISHOP_OFFSET = new int[SQUARES];
  private static final int[] ROOK_OFFSET = new int[SQUARES];

  // One flat table per piece rather than long[64][]: the offset costs an extra array read but keeps the whole table in
  // one contiguous allocation instead of 64 separately-placed rows.
  private static final long[] BISHOP_ATTACKS;
  private static final long[] ROOK_ATTACKS;

  static {
    for (int square = 0; square < SQUARES; square++) {
      BISHOP_MASK[square] = bishopRelevantMask(square);
      ROOK_MASK[square] = rookRelevantMask(square);
      BISHOP_SHIFT[square] = 64 - Long.bitCount(BISHOP_MASK[square]);
      ROOK_SHIFT[square] = 64 - Long.bitCount(ROOK_MASK[square]);
    }

    int bishopTotal = 0;
    int rookTotal = 0;
    for (int square = 0; square < SQUARES; square++) {
      BISHOP_OFFSET[square] = bishopTotal;
      ROOK_OFFSET[square] = rookTotal;
      bishopTotal += 1 << (64 - BISHOP_SHIFT[square]);
      rookTotal += 1 << (64 - ROOK_SHIFT[square]);
    }
    BISHOP_ATTACKS = new long[bishopTotal];
    ROOK_ATTACKS = new long[rookTotal];

    for (int square = 0; square < SQUARES; square++) {
      fillSquare(square, true);
      fillSquare(square, false);
    }
  }

  private MagicSliderAttacks() {
  }

  /** Bishop attacks from {@code squareOrdinal} (0..63) given {@code occupied}. */
  public static long bishop(int squareOrdinal, long occupied) {
    final int index = (int) (((occupied & BISHOP_MASK[squareOrdinal]) * BISHOP_MAGIC[squareOrdinal])
        >>> BISHOP_SHIFT[squareOrdinal]);
    return BISHOP_ATTACKS[BISHOP_OFFSET[squareOrdinal] + index];
  }

  /** Rook attacks from {@code squareOrdinal} (0..63) given {@code occupied}. */
  public static long rook(int squareOrdinal, long occupied) {
    final int index = (int) (((occupied & ROOK_MASK[squareOrdinal]) * ROOK_MAGIC[squareOrdinal])
        >>> ROOK_SHIFT[squareOrdinal]);
    return ROOK_ATTACKS[ROOK_OFFSET[squareOrdinal] + index];
  }

  /** Combined entry count of both attack tables. Multiply by {@code Long.BYTES} for the footprint in bytes. */
  public static int tableEntryCount() {
    return BISHOP_ATTACKS.length + ROOK_ATTACKS.length;
  }

  // Fills one square's slice of the attack table, rejecting a magic that maps two different attack sets onto the same
  // index. The carry-rippler enumerates subsets of a mask without ever setting a bit outside it.
  private static void fillSquare(int square, boolean isBishop) {
    final long mask = isBishop ? BISHOP_MASK[square] : ROOK_MASK[square];
    final long magic = isBishop ? BISHOP_MAGIC[square] : ROOK_MAGIC[square];
    final int shift = isBishop ? BISHOP_SHIFT[square] : ROOK_SHIFT[square];
    final int offset = isBishop ? BISHOP_OFFSET[square] : ROOK_OFFSET[square];
    final long[] target = isBishop ? BISHOP_ATTACKS : ROOK_ATTACKS;
    final int size = 1 << (64 - shift);

    final boolean[] written = new boolean[size];
    long subset = 0L;
    do {
      final long reference = isBishop ? SliderRayAttacks.bishop(square, subset) : SliderRayAttacks.rook(square, subset);
      final int index = (int) ((subset * magic) >>> shift);
      if (written[index] && target[offset + index] != reference) {
        throw new ProgrammingMistakeException("Magic constant for square " + square + " (isBishop=" + isBishop
            + ") collides: occupancy " + Long.toHexString(subset) + " and an earlier one share index " + index
            + " with different attack sets. The constant does not match the current mask; regenerate it.");
      }
      written[index] = true;
      target[offset + index] = reference;
      subset = (subset - mask) & mask;
    } while (subset != 0L);
  }

  // Diagonal squares, excluding the square itself and the board edge: an edge square cannot block anything further
  // along the ray, so it carries no information and stays out of the index.
  private static long bishopRelevantMask(int square) {
    final int file = square & 7;
    final int rank = square >> 3;
    long mask = 0L;
    for (int fileStep = -1; fileStep <= 1; fileStep += 2) {
      for (int rankStep = -1; rankStep <= 1; rankStep += 2) {
        int currentFile = file + fileStep;
        int currentRank = rank + rankStep;
        while (currentFile >= 1 && currentFile <= 6 && currentRank >= 1 && currentRank <= 6) {
          mask |= 1L << ((currentRank << 3) | currentFile);
          currentFile += fileStep;
          currentRank += rankStep;
        }
      }
    }
    return mask;
  }

  // Rank and file squares, excluding the square itself and the last square of each ray, for the same reason as the
  // bishop mask. The bound is per direction, not a global border: a rook on a1 still has b1..g1 and a2..a7 relevant.
  private static long rookRelevantMask(int square) {
    final int file = square & 7;
    final int rank = square >> 3;
    long mask = 0L;
    for (int currentRank = rank + 1; currentRank <= 6; currentRank++) {
      mask |= 1L << ((currentRank << 3) | file);
    }
    for (int currentRank = rank - 1; currentRank >= 1; currentRank--) {
      mask |= 1L << ((currentRank << 3) | file);
    }
    for (int currentFile = file + 1; currentFile <= 6; currentFile++) {
      mask |= 1L << ((rank << 3) | currentFile);
    }
    for (int currentFile = file - 1; currentFile >= 1; currentFile--) {
      mask |= 1L << ((rank << 3) | currentFile);
    }
    return mask;
  }
}
