// Copyright (C) 2020-2026 Daniel Baechli
// SPDX-License-Identifier: GPL-3.0-only

package io.github.dlbbld.ashlarchess.test.oracle.python;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.junit.jupiter.api.Test;

import io.github.dlbbld.ashlarchess.internal.Nulls;
import io.github.dlbbld.ashlarchess.pgn.LenientPgnParser;
import io.github.dlbbld.ashlarchess.pgn.Nag;
import io.github.dlbbld.ashlarchess.pgn.PgnCreate;
import io.github.dlbbld.ashlarchess.pgn.PgnGame;
import io.github.dlbbld.ashlarchess.pgn.PgnMove;
import io.github.dlbbld.ashlarchess.pgn.WriteMode;
import io.github.dlbbld.ashlarchess.test.ConfigurationTestConstants;

/**
 * Cross-validates ashlar-chess's archival NAG serialisation against python-chess. For each fixture under
 * {@code src/test/resources/pgnNagExport/}, python-chess's own movetext export and per-move NAG sets are captured in
 * {@code src/test/resources/oracle/python-chess/nagExport.jsonl} (generated by
 * {@code src/test/python/generate_nag_export_oracle.py}); this test parses the same fixture with ashlar-chess, emits
 * {@link WriteMode#ARCHIVAL}, and asserts its movetext equals python-chess's export and its per-move NAG codes equal
 * python-chess's set.
 *
 * <p>
 * Both libraries treat the six suffix glyphs as import shorthand for NAG codes 1..6 and write every NAG as {@code $N} in
 * export/archival form. Archival export is also <em>canonical</em>: ashlar-chess deduplicates and sorts a move's NAGs
 * ascending, matching how python-chess holds them in a set - so the two serialisations coincide byte-for-byte even when
 * the source order is scrambled or carries duplicates (fixtures 06/07). The fixtures carry no variations (ashlar skips
 * those; python-chess models them). The per-move code comparison also deduplicates and sorts ashlar's parsed list.
 */
class TestPgnArchivalExportAgainstPythonChessOracle {

  private static final Path FIXTURE_DIR = Nulls.pathResolve(ConfigurationTestConstants.PROJECT_ROOT_FOLDER_PATH,
      "src/test/resources/pgnNagExport");
  private static final Path ORACLE_PATH = Nulls.pathResolve(ConfigurationTestConstants.PROJECT_ROOT_FOLDER_PATH,
      "src/test/resources/oracle/python-chess/nagExport.jsonl");

  @SuppressWarnings({ "static-method", "unchecked" })
  @Test
  void archivalNagExportMatchesPythonChess() throws IOException {
    final List<String> lines = Files.readAllLines(ORACLE_PATH, StandardCharsets.UTF_8);
    int fixtures = 0;
    for (int li = 0; li < lines.size(); li++) {
      final String line = Nulls.get(lines, li);
      if (line.isBlank()) {
        continue;
      }
      fixtures++;
      final Map<String, Object> record = OracleJsonlReader.parseLineToObject(line);
      final String pgn = (String) record.get("pgn");
      final String expectedMovetext = (String) record.get("movetext");
      final List<Object> expectedNags = (List<Object>) record.get("nags");

      final PgnGame game = LenientPgnParser.parsePath(FIXTURE_DIR, pgn);

      // (1) direct export comparison: ashlar archival movetext == python-chess export movetext.
      final String archival = PgnCreate.toPgnString(game, WriteMode.ARCHIVAL);
      assertEquals(expectedMovetext, movetextOf(archival), () -> pgn + " - archival movetext disagrees with python-chess");

      // (2) semantic agreement: the same NAG codes per move (dedup + sorted, so the list-vs-set difference is neutral).
      assertEquals(expectedNags.size(), game.moves().size(), () -> pgn + " - move count");
      for (int i = 0; i < game.moves().size(); i++) {
        final List<Integer> expected = new ArrayList<>();
        for (final Object code : (List<Object>) Nulls.get(expectedNags, i)) {
          expected.add((Integer) code);
        }
        final int index = i;
        assertEquals(expected, distinctSortedCodes(Nulls.get(game.moves(), i)),
            () -> pgn + " - NAG codes at move " + index);
      }
    }
    assertFalse(fixtures == 0, "no NAG export fixtures were checked - oracle missing or empty");
  }

  /** Reconstructs the movetext from an exported PGN: drop tag lines and blanks, join the rest with single spaces. */
  private static String movetextOf(String pgn) {
    final StringBuilder movetext = new StringBuilder();
    final String[] rawLines = Nulls.split(Nulls.replace(pgn, "\r\n", "\n"), "\n");
    for (int i = 0; i < rawLines.length; i++) {
      final String line = Nulls.trim(Nulls.get(rawLines, i));
      if (line.isEmpty() || line.startsWith("[")) {
        continue;
      }
      if (movetext.length() > 0) {
        movetext.append(' ');
      }
      movetext.append(line);
    }
    return Nulls.toString(movetext);
  }

  private static List<Integer> distinctSortedCodes(PgnMove move) {
    final List<Integer> codes = new ArrayList<>();
    for (final Nag nag : move.nags()) {
      if (!codes.contains(nag.code())) {
        codes.add(nag.code());
      }
    }
    codes.sort(null);
    return codes;
  }
}
